// This file is auto-generated by generate-method-metadata.mjs

export const methodMetadata = {
  "Mood.moodGet": {
    "operationId": "mood-get",
    "summary": "Get mood log",
    "description": "Get a single mood log by ID",
    "httpMethod": "POST",
    "path": "/mood/get",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "Mood.moodList": {
    "operationId": "mood-list",
    "summary": "List mood logs",
    "description": "List mood logs for a date range",
    "httpMethod": "POST",
    "path": "/mood/list",
    "exampleInput": {
      "body": {
        "date": {
          "year": 1,
          "month": 1,
          "day": 1
        }
      }
    }
  },
  "Mood.moodGetForWidget": {
    "operationId": "mood-getForWidget",
    "summary": "Get mood widget data",
    "description": "Get aggregated mood data for widgets",
    "httpMethod": "POST",
    "path": "/mood/widget",
    "exampleInput": {
      "body": {
        "date": {
          "year": 1,
          "month": 1,
          "day": 1
        }
      }
    }
  },
  "Mood.moodCreate": {
    "operationId": "mood-create",
    "summary": "Create mood log",
    "description": "Create a new mood log",
    "httpMethod": "POST",
    "path": "/mood",
    "exampleInput": {
      "body": {
        "mood": 4
      }
    }
  },
  "Mood.moodUpdate": {
    "operationId": "mood-update",
    "summary": "Update mood log",
    "description": "Update an existing mood log",
    "httpMethod": "POST",
    "path": "/mood/update",
    "exampleInput": {
      "body": {
        "id": "item_123",
        "data": {
          "note": "Example",
          "mood": 4
        }
      }
    }
  },
  "Mood.moodDelete": {
    "operationId": "mood-delete",
    "summary": "Delete mood log",
    "description": "Delete a mood log",
    "httpMethod": "POST",
    "path": "/mood/delete",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "Mood.moodDeleteMany": {
    "operationId": "mood-deleteMany",
    "summary": "Delete multiple mood logs",
    "description": "Delete multiple mood logs",
    "httpMethod": "POST",
    "path": "/mood/delete-many",
    "exampleInput": {
      "body": {
        "ids": [
          "item_123"
        ]
      }
    }
  },
  "Mood.moodDeleteAll": {
    "operationId": "mood-deleteAll",
    "summary": "Delete all mood logs",
    "description": "Delete all mood logs for the user",
    "httpMethod": "POST",
    "path": "/mood/delete-all",
    "exampleInput": {
      "body": {}
    }
  },
  "PainEvents.painEventsBodyParts": {
    "operationId": "painEvents-bodyParts",
    "summary": "List body parts",
    "description": "List available pain event body parts",
    "httpMethod": "POST",
    "path": "/pain-events/body-parts/list"
  },
  "PainEvents.painEventsRecentBodyParts": {
    "operationId": "painEvents-recentBodyParts",
    "summary": "Recent body parts",
    "description": "List recently used pain event body parts",
    "httpMethod": "POST",
    "path": "/pain-events/recent-body-parts"
  },
  "PainEvents.painEventsGet": {
    "operationId": "painEvents-get",
    "summary": "Get pain event",
    "description": "Get a single pain event by ID",
    "httpMethod": "POST",
    "path": "/pain-events/get",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "PainEvents.painEventsList": {
    "operationId": "painEvents-list",
    "summary": "List pain events",
    "description": "List pain events for a date range",
    "httpMethod": "POST",
    "path": "/pain-events/list",
    "exampleInput": {
      "body": {
        "date": {
          "year": 1,
          "month": 1,
          "day": 1
        }
      }
    }
  },
  "PainEvents.painEventsCreate": {
    "operationId": "painEvents-create",
    "summary": "Create pain event",
    "description": "Create a new pain event",
    "httpMethod": "POST",
    "path": "/pain-events",
    "exampleInput": {
      "body": {
        "date": {
          "timezone": "Europe/Warsaw",
          "dateInUsersTimezone": "2026-03-30"
        },
        "painLevel": 1,
        "bodyPartId": "bodypart_123"
      }
    }
  },
  "PainEvents.painEventsUpdate": {
    "operationId": "painEvents-update",
    "summary": "Update pain event",
    "description": "Update an existing pain event",
    "httpMethod": "POST",
    "path": "/pain-events/update",
    "exampleInput": {
      "body": {
        "id": "item_123",
        "data": {
          "date": {
            "timezone": "Europe/Warsaw",
            "dateInUsersTimezone": "2026-03-30"
          },
          "painLevel": 1
        }
      }
    }
  },
  "PainEvents.painEventsDelete": {
    "operationId": "painEvents-delete",
    "summary": "Delete pain event",
    "description": "Delete a pain event",
    "httpMethod": "POST",
    "path": "/pain-events/delete",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "PainEvents.painEventsDeleteMany": {
    "operationId": "painEvents-deleteMany",
    "summary": "Delete multiple pain events",
    "description": "Delete multiple pain events",
    "httpMethod": "POST",
    "path": "/pain-events/delete-many",
    "exampleInput": {
      "body": {
        "ids": [
          "item_123"
        ]
      }
    }
  },
  "Trips.tripsGet": {
    "operationId": "trips-get",
    "summary": "Get trip",
    "description": "Get a single trip by ID",
    "httpMethod": "POST",
    "path": "/trips/get",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "Trips.tripsList": {
    "operationId": "trips-list",
    "summary": "List trips",
    "description": "List trips for the current user",
    "httpMethod": "POST",
    "path": "/trips/list"
  },
  "Trips.tripsCreate": {
    "operationId": "trips-create",
    "summary": "Create trip",
    "description": "Create a new trip",
    "httpMethod": "POST",
    "path": "/trips",
    "exampleInput": {
      "body": {
        "name": "Example"
      }
    }
  },
  "Trips.tripsUpdate": {
    "operationId": "trips-update",
    "summary": "Update trip",
    "description": "Update an existing trip",
    "httpMethod": "POST",
    "path": "/trips/update",
    "exampleInput": {
      "body": {
        "id": "item_123",
        "data": {
          "name": "Example",
          "transportMethod": "Other"
        }
      }
    }
  },
  "Trips.tripsDelete": {
    "operationId": "trips-delete",
    "summary": "Delete trip",
    "description": "Delete a trip",
    "httpMethod": "POST",
    "path": "/trips/delete",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "Trips.tripsDeleteMany": {
    "operationId": "trips-deleteMany",
    "summary": "Delete multiple trips",
    "description": "Delete multiple trips",
    "httpMethod": "POST",
    "path": "/trips/delete-many",
    "exampleInput": {
      "body": {
        "ids": [
          "item_123"
        ]
      }
    }
  },
  "PackingActivities.packingActivitiesGet": {
    "operationId": "packingActivities-get",
    "summary": "Get packing activity",
    "description": "Get a single packing activity by ID",
    "httpMethod": "POST",
    "path": "/packing-activities/get",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "PackingActivities.packingActivitiesList": {
    "operationId": "packingActivities-list",
    "summary": "List packing activities",
    "description": "List packing activities for the current user",
    "httpMethod": "POST",
    "path": "/packing-activities/list"
  },
  "PackingActivities.packingActivitiesCreate": {
    "operationId": "packingActivities-create",
    "summary": "Create packing activity",
    "description": "Create a new packing activity",
    "httpMethod": "POST",
    "path": "/packing-activities",
    "exampleInput": {
      "body": {
        "name": "Example"
      }
    }
  },
  "PackingActivities.packingActivitiesUpdate": {
    "operationId": "packingActivities-update",
    "summary": "Update packing activity",
    "description": "Update an existing packing activity",
    "httpMethod": "POST",
    "path": "/packing-activities/update",
    "exampleInput": {
      "body": {
        "id": "item_123",
        "data": {
          "emoji": "string",
          "name": "Example"
        }
      }
    }
  },
  "PackingActivities.packingActivitiesDelete": {
    "operationId": "packingActivities-delete",
    "summary": "Delete packing activity",
    "description": "Delete a packing activity",
    "httpMethod": "POST",
    "path": "/packing-activities/delete",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "PackingActivities.packingActivitiesDeleteMany": {
    "operationId": "packingActivities-deleteMany",
    "summary": "Delete multiple packing activities",
    "description": "Delete multiple packing activities",
    "httpMethod": "POST",
    "path": "/packing-activities/delete-many",
    "exampleInput": {
      "body": {
        "ids": [
          "item_123"
        ]
      }
    }
  },
  "PackingActivities.packingActivitiesExists": {
    "operationId": "packingActivities-exists",
    "summary": "Check packing activity exists",
    "description": "Check whether a packing activity exists",
    "httpMethod": "POST",
    "path": "/packing-activities/exists",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "PackingItems.packingItemsGet": {
    "operationId": "packingItems-get",
    "summary": "Get packing item",
    "description": "Get a single packing item by ID",
    "httpMethod": "POST",
    "path": "/packing-items/get",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "PackingItems.packingItemsList": {
    "operationId": "packingItems-list",
    "summary": "List packing items",
    "description": "List packing items for the current user",
    "httpMethod": "POST",
    "path": "/packing-items/list",
    "exampleInput": {
      "body": {
        "tripId": "trip_123",
        "activityId": "activity_123"
      }
    }
  },
  "PackingItems.packingItemsCreate": {
    "operationId": "packingItems-create",
    "summary": "Create packing item",
    "description": "Create a new packing item",
    "httpMethod": "POST",
    "path": "/packing-items",
    "exampleInput": {
      "body": {
        "name": "Example"
      }
    }
  },
  "PackingItems.packingItemsUpdate": {
    "operationId": "packingItems-update",
    "summary": "Update packing item",
    "description": "Update an existing packing item",
    "httpMethod": "POST",
    "path": "/packing-items/update",
    "exampleInput": {
      "body": {
        "id": "item_123",
        "data": {
          "defaultQuantity": 1,
          "quantityPerDay": true
        }
      }
    }
  },
  "PackingItems.packingItemsDelete": {
    "operationId": "packingItems-delete",
    "summary": "Delete packing item",
    "description": "Delete a packing item",
    "httpMethod": "POST",
    "path": "/packing-items/delete",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "PackingItems.packingItemsDeleteMany": {
    "operationId": "packingItems-deleteMany",
    "summary": "Delete multiple packing items",
    "description": "Delete multiple packing items",
    "httpMethod": "POST",
    "path": "/packing-items/delete-many",
    "exampleInput": {
      "body": {
        "ids": [
          "item_123"
        ]
      }
    }
  },
  "Transports.transportsGet": {
    "operationId": "transports-get",
    "summary": "Get transport",
    "description": "Get a single transport by ID",
    "httpMethod": "POST",
    "path": "/transports/get",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "Transports.transportsList": {
    "operationId": "transports-list",
    "summary": "List transports",
    "description": "List transports for the current user",
    "httpMethod": "POST",
    "path": "/transports/list",
    "exampleInput": {
      "body": {
        "onlyFuture": true
      }
    }
  },
  "Transports.transportsCreate": {
    "operationId": "transports-create",
    "summary": "Create transport",
    "description": "Create a new transport",
    "httpMethod": "POST",
    "path": "/transports",
    "exampleInput": {
      "body": {
        "name": "Example"
      }
    }
  },
  "Transports.transportsUpdate": {
    "operationId": "transports-update",
    "summary": "Update transport",
    "description": "Update an existing transport",
    "httpMethod": "POST",
    "path": "/transports/update",
    "exampleInput": {
      "body": {
        "id": "item_123",
        "data": {
          "type": "Plane",
          "name": "Example"
        }
      }
    }
  },
  "Transports.transportsDelete": {
    "operationId": "transports-delete",
    "summary": "Delete transport",
    "description": "Delete a transport",
    "httpMethod": "POST",
    "path": "/transports/delete",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "Transports.transportsDeleteMany": {
    "operationId": "transports-deleteMany",
    "summary": "Delete multiple transports",
    "description": "Delete multiple transports",
    "httpMethod": "POST",
    "path": "/transports/delete-many",
    "exampleInput": {
      "body": {
        "ids": [
          "item_123"
        ]
      }
    }
  },
  "Transports.transportsExists": {
    "operationId": "transports-exists",
    "summary": "Check transport exists",
    "description": "Check whether a transport exists",
    "httpMethod": "POST",
    "path": "/transports/exists",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "Stays.staysGet": {
    "operationId": "stays-get",
    "summary": "Get stay",
    "description": "Get a single stay by ID",
    "httpMethod": "POST",
    "path": "/stays/get",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "Stays.staysList": {
    "operationId": "stays-list",
    "summary": "List stays",
    "description": "List stays for the current user",
    "httpMethod": "POST",
    "path": "/stays/list",
    "exampleInput": {
      "body": {
        "onlyFuture": true
      }
    }
  },
  "Stays.staysCreate": {
    "operationId": "stays-create",
    "summary": "Create stay",
    "description": "Create a new stay",
    "httpMethod": "POST",
    "path": "/stays",
    "exampleInput": {
      "body": {
        "name": "Example"
      }
    }
  },
  "Stays.staysUpdate": {
    "operationId": "stays-update",
    "summary": "Update stay",
    "description": "Update an existing stay",
    "httpMethod": "POST",
    "path": "/stays/update",
    "exampleInput": {
      "body": {
        "id": "item_123",
        "data": {
          "type": "Hotel",
          "name": "Example"
        }
      }
    }
  },
  "Stays.staysDelete": {
    "operationId": "stays-delete",
    "summary": "Delete stay",
    "description": "Delete a stay",
    "httpMethod": "POST",
    "path": "/stays/delete",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "Stays.staysDeleteMany": {
    "operationId": "stays-deleteMany",
    "summary": "Delete multiple stays",
    "description": "Delete multiple stays",
    "httpMethod": "POST",
    "path": "/stays/delete-many",
    "exampleInput": {
      "body": {
        "ids": [
          "item_123"
        ]
      }
    }
  },
  "PlannerEvents.plannerEventsGet": {
    "operationId": "plannerEvents-get",
    "summary": "Get planner event",
    "description": "Get a single planner event by ID",
    "httpMethod": "POST",
    "path": "/planner-events/get",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "PlannerEvents.plannerEventsList": {
    "operationId": "plannerEvents-list",
    "summary": "List planner events",
    "description": "List planner events for the current user",
    "httpMethod": "POST",
    "path": "/planner-events/list",
    "exampleInput": {
      "body": {
        "startDate": "2026-03-30",
        "endDate": "2026-03-30"
      }
    }
  },
  "PlannerEvents.plannerEventsCreate": {
    "operationId": "plannerEvents-create",
    "summary": "Create planner event",
    "description": "Create a new planner event",
    "httpMethod": "POST",
    "path": "/planner-events",
    "exampleInput": {
      "body": {
        "start": {
          "timezone": "Europe/Warsaw",
          "dateInUsersTimezone": "2026-03-30"
        }
      }
    }
  },
  "PlannerEvents.plannerEventsUpdate": {
    "operationId": "plannerEvents-update",
    "summary": "Update planner event",
    "description": "Update an existing planner event",
    "httpMethod": "POST",
    "path": "/planner-events/update",
    "exampleInput": {
      "body": {
        "id": "item_123",
        "data": {
          "title": "Example",
          "emoji": "string"
        }
      }
    }
  },
  "PlannerEvents.plannerEventsDelete": {
    "operationId": "plannerEvents-delete",
    "summary": "Delete planner event",
    "description": "Delete a planner event",
    "httpMethod": "POST",
    "path": "/planner-events/delete",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "PlannerEvents.plannerEventsDeleteMany": {
    "operationId": "plannerEvents-deleteMany",
    "summary": "Delete multiple planner events",
    "description": "Delete multiple planner events",
    "httpMethod": "POST",
    "path": "/planner-events/delete-many",
    "exampleInput": {
      "body": {
        "ids": [
          "item_123"
        ]
      }
    }
  },
  "Todos.todosGet": {
    "operationId": "todos-get",
    "summary": "Get todo",
    "description": "Get a single todo by ID",
    "httpMethod": "POST",
    "path": "/todos/get",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "Todos.todosList": {
    "operationId": "todos-list",
    "summary": "List todos",
    "description": "List todos with filters",
    "httpMethod": "POST",
    "path": "/todos/list",
    "exampleInput": {
      "body": {
        "screen": "today",
        "date": "2026-03-30"
      }
    }
  },
  "Todos.todosByTag": {
    "operationId": "todos-byTag",
    "summary": "List todos by tag",
    "description": "List todos filtered by tag ID",
    "httpMethod": "POST",
    "path": "/todos/by-tag/list",
    "exampleInput": {
      "body": {
        "tagId": "tag_123"
      }
    }
  },
  "Todos.todosByProject": {
    "operationId": "todos-byProject",
    "summary": "List todos by project",
    "description": "List todos filtered by project ID",
    "httpMethod": "POST",
    "path": "/todos/by-project/list",
    "exampleInput": {
      "body": {
        "projectId": "project_123"
      }
    }
  },
  "Todos.todosByList": {
    "operationId": "todos-byList",
    "summary": "List todos by list",
    "description": "List todos filtered by list ID",
    "httpMethod": "POST",
    "path": "/todos/by-list/list",
    "exampleInput": {
      "body": {
        "listId": "list_123"
      }
    }
  },
  "Todos.todosExists": {
    "operationId": "todos-exists",
    "summary": "Check todo existence",
    "description": "Check if a todo exists",
    "httpMethod": "POST",
    "path": "/todos/exists",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "Todos.todosCreate": {
    "operationId": "todos-create",
    "summary": "Create todo",
    "description": "Create a new todo",
    "httpMethod": "POST",
    "path": "/todos",
    "exampleInput": {
      "body": {
        "title": "Example"
      }
    }
  },
  "Todos.todosUpdate": {
    "operationId": "todos-update",
    "summary": "Update todo",
    "description": "Update an existing todo",
    "httpMethod": "POST",
    "path": "/todos/update",
    "exampleInput": {
      "body": {
        "id": "item_123",
        "data": {
          "title": "Example",
          "description": "Example"
        }
      }
    }
  },
  "Todos.todosToggle": {
    "operationId": "todos-toggle",
    "summary": "Toggle todo completion",
    "description": "Toggle the completion status of a todo",
    "httpMethod": "POST",
    "path": "/todos/toggle",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "Todos.todosDelete": {
    "operationId": "todos-delete",
    "summary": "Delete todo",
    "description": "Delete a todo",
    "httpMethod": "POST",
    "path": "/todos/delete",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "Todos.todosDeleteMany": {
    "operationId": "todos-deleteMany",
    "summary": "Delete multiple todos",
    "description": "Delete multiple todos",
    "httpMethod": "POST",
    "path": "/todos/delete-many",
    "exampleInput": {
      "body": {
        "ids": [
          "item_123"
        ]
      }
    }
  },
  "Todos.todosQuickUpdateMany": {
    "operationId": "todos-quickUpdateMany",
    "summary": "Quick update multiple todos",
    "description": "Quickly update multiple todos with common fields",
    "httpMethod": "POST",
    "path": "/todos/quick-update-many",
    "exampleInput": {
      "body": {
        "ids": [
          "item_123"
        ],
        "data": {
          "title": "Example",
          "description": "Example"
        }
      }
    }
  },
  "Todos.todosAssign": {
    "operationId": "todos-assign",
    "summary": "Assign user to todo",
    "description": "Assign a user to a todo",
    "httpMethod": "POST",
    "path": "/todos/assign",
    "exampleInput": {
      "body": {
        "todoId": "todo_123",
        "userId": "user_123"
      }
    }
  },
  "Todos.todosUnassign": {
    "operationId": "todos-unassign",
    "summary": "Unassign user from todo",
    "description": "Unassign a user from a todo",
    "httpMethod": "POST",
    "path": "/todos/unassign",
    "exampleInput": {
      "body": {
        "todoId": "todo_123",
        "userId": "user_123"
      }
    }
  },
  "Todos.todosAssignableUsers": {
    "operationId": "todos-assignableUsers",
    "summary": "Get assignable users",
    "description": "Get all users that can be assigned to todos (from shared lists/projects)",
    "httpMethod": "POST",
    "path": "/todos/assignable-users"
  },
  "Todos.todosPossibleAssignees": {
    "operationId": "todos-possibleAssignees",
    "summary": "Get possible assignees",
    "description": "Get possible assignees for a specific list or project",
    "httpMethod": "POST",
    "path": "/todos/possible-assignees",
    "exampleInput": {
      "body": {
        "listId": "list_123",
        "projectId": "project_123"
      }
    }
  },
  "Assignments.todosAssign": {
    "operationId": "todos-assign",
    "summary": "Assign user to todo",
    "description": "Assign a user to a todo",
    "httpMethod": "POST",
    "path": "/todos/assign",
    "exampleInput": {
      "body": {
        "todoId": "todo_123",
        "userId": "user_123"
      }
    }
  },
  "Assignments.todosUnassign": {
    "operationId": "todos-unassign",
    "summary": "Unassign user from todo",
    "description": "Unassign a user from a todo",
    "httpMethod": "POST",
    "path": "/todos/unassign",
    "exampleInput": {
      "body": {
        "todoId": "todo_123",
        "userId": "user_123"
      }
    }
  },
  "Assignments.todosAssignableUsers": {
    "operationId": "todos-assignableUsers",
    "summary": "Get assignable users",
    "description": "Get all users that can be assigned to todos (from shared lists/projects)",
    "httpMethod": "POST",
    "path": "/todos/assignable-users"
  },
  "Assignments.todosPossibleAssignees": {
    "operationId": "todos-possibleAssignees",
    "summary": "Get possible assignees",
    "description": "Get possible assignees for a specific list or project",
    "httpMethod": "POST",
    "path": "/todos/possible-assignees",
    "exampleInput": {
      "body": {
        "listId": "list_123",
        "projectId": "project_123"
      }
    }
  },
  "Tags.tagsList": {
    "operationId": "tags-list",
    "summary": "List tags",
    "description": "List tags for the current user",
    "httpMethod": "POST",
    "path": "/tags/list",
    "exampleInput": {
      "body": {
        "taskType": "personal"
      }
    }
  },
  "Tags.tagsGet": {
    "operationId": "tags-get",
    "summary": "Get tag",
    "description": "Get a single tag by ID",
    "httpMethod": "POST",
    "path": "/tags/get",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "Tags.tagsCreate": {
    "operationId": "tags-create",
    "summary": "Create tag",
    "description": "Create a new tag",
    "httpMethod": "POST",
    "path": "/tags",
    "exampleInput": {
      "body": {
        "name": "Example"
      }
    }
  },
  "Tags.tagsUpdate": {
    "operationId": "tags-update",
    "summary": "Update tag",
    "description": "Update an existing tag",
    "httpMethod": "POST",
    "path": "/tags/update",
    "exampleInput": {
      "body": {
        "id": "item_123",
        "data": {
          "name": "Example",
          "points": 1
        }
      }
    }
  },
  "Tags.tagsDelete": {
    "operationId": "tags-delete",
    "summary": "Delete tag",
    "description": "Delete a tag",
    "httpMethod": "POST",
    "path": "/tags/delete",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "Tags.tagsExists": {
    "operationId": "tags-exists",
    "summary": "Check tag exists",
    "description": "Check whether a tag exists",
    "httpMethod": "POST",
    "path": "/tags/exists",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "Tags.tagsForTodoForm": {
    "operationId": "tags-forTodoForm",
    "summary": "Tags for todo form",
    "description": "List tags, tag groups, and favorites for the todo form",
    "httpMethod": "POST",
    "path": "/tags/for-todo-form",
    "exampleInput": {
      "body": {
        "taskType": "personal"
      }
    }
  },
  "Tags.tagsFavorites": {
    "operationId": "tags-favorites",
    "summary": "Favorite tags",
    "description": "List favorite tags by usage",
    "httpMethod": "POST",
    "path": "/tags/favorites",
    "exampleInput": {
      "body": {
        "limit": 10,
        "taskType": "personal"
      }
    }
  },
  "Projects.projectsList": {
    "operationId": "projects-list",
    "summary": "List projects",
    "description": "List projects for the current user",
    "httpMethod": "POST",
    "path": "/projects/list",
    "exampleInput": {
      "body": {
        "taskType": "personal"
      }
    }
  },
  "Projects.projectsGet": {
    "operationId": "projects-get",
    "summary": "Get project",
    "description": "Get a single project by ID",
    "httpMethod": "POST",
    "path": "/projects/get",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "Projects.projectsCreate": {
    "operationId": "projects-create",
    "summary": "Create project",
    "description": "Create a new project",
    "httpMethod": "POST",
    "path": "/projects",
    "exampleInput": {
      "body": {
        "name": "Example"
      }
    }
  },
  "Projects.projectsUpdate": {
    "operationId": "projects-update",
    "summary": "Update project",
    "description": "Update an existing project",
    "httpMethod": "POST",
    "path": "/projects/update",
    "exampleInput": {
      "body": {
        "id": "item_123",
        "data": {
          "name": "Example",
          "description": "Example"
        }
      }
    }
  },
  "Projects.projectsDelete": {
    "operationId": "projects-delete",
    "summary": "Delete project",
    "description": "Delete a project",
    "httpMethod": "POST",
    "path": "/projects/delete",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "Projects.projectsExists": {
    "operationId": "projects-exists",
    "summary": "Check project exists",
    "description": "Check whether a project exists",
    "httpMethod": "POST",
    "path": "/projects/exists",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "Projects.projectsForTodoForm": {
    "operationId": "projects-forTodoForm",
    "summary": "Projects for todo form",
    "description": "List projects for the todo form",
    "httpMethod": "POST",
    "path": "/projects/for-todo-form",
    "exampleInput": {
      "body": {
        "taskType": "personal"
      }
    }
  },
  "TodoLists.todoListsList": {
    "operationId": "todoLists-list",
    "summary": "List todo lists",
    "description": "List todo lists for the current user",
    "httpMethod": "POST",
    "path": "/todo-lists/list",
    "exampleInput": {
      "body": {
        "taskType": "personal"
      }
    }
  },
  "TodoLists.todoListsGet": {
    "operationId": "todoLists-get",
    "summary": "Get todo list",
    "description": "Get a single todo list by ID",
    "httpMethod": "POST",
    "path": "/todo-lists/get",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "TodoLists.todoListsFavorites": {
    "operationId": "todoLists-favorites",
    "summary": "Favorite todo lists",
    "description": "List favorite todo lists by usage",
    "httpMethod": "POST",
    "path": "/todo-lists/favorites",
    "exampleInput": {
      "body": {
        "limit": 10,
        "taskType": "personal"
      }
    }
  },
  "TodoLists.todoListsCreate": {
    "operationId": "todoLists-create",
    "summary": "Create todo list",
    "description": "Create a new todo list",
    "httpMethod": "POST",
    "path": "/todo-lists",
    "exampleInput": {
      "body": {
        "name": "Example"
      }
    }
  },
  "TodoLists.todoListsUpdate": {
    "operationId": "todoLists-update",
    "summary": "Update todo list",
    "description": "Update an existing todo list",
    "httpMethod": "POST",
    "path": "/todo-lists/update",
    "exampleInput": {
      "body": {
        "id": "item_123",
        "data": {
          "name": "Example",
          "emoji": "string"
        }
      }
    }
  },
  "TodoLists.todoListsDelete": {
    "operationId": "todoLists-delete",
    "summary": "Delete todo list",
    "description": "Delete a todo list",
    "httpMethod": "POST",
    "path": "/todo-lists/delete",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "TodoLists.todoListsExists": {
    "operationId": "todoLists-exists",
    "summary": "Check todo list exists",
    "description": "Check whether a todo list exists",
    "httpMethod": "POST",
    "path": "/todo-lists/exists",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "TodoLists.todoListsForTodoForm": {
    "operationId": "todoLists-forTodoForm",
    "summary": "Todo lists for todo form",
    "description": "List todo lists for the todo form",
    "httpMethod": "POST",
    "path": "/todo-lists/for-todo-form",
    "exampleInput": {
      "body": {
        "taskType": "personal"
      }
    }
  },
  "Habits.habitsGetHabitsAndCompletions": {
    "operationId": "habits-getHabitsAndCompletions",
    "summary": "Get habits with completions",
    "description": "Get habits with completions for a date range",
    "httpMethod": "POST",
    "path": "/habits/with-completions",
    "exampleInput": {
      "body": {
        "dateFrom": "2026-03-30",
        "dateTo": "2026-03-30"
      }
    }
  },
  "Habits.habitsGetHabitsForCurrentUser": {
    "operationId": "habits-getHabitsForCurrentUser",
    "summary": "Get all habits",
    "description": "Get all habits for the authenticated user",
    "httpMethod": "POST",
    "path": "/habits/list"
  },
  "Habits.habitsGet": {
    "operationId": "habits-get",
    "summary": "Get single habit",
    "description": "Get a single habit by ID",
    "httpMethod": "POST",
    "path": "/habits/get",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "Habits.habitsCreate": {
    "operationId": "habits-create",
    "summary": "Create habit",
    "description": "Create a new habit",
    "httpMethod": "POST",
    "path": "/habits",
    "exampleInput": {
      "body": {
        "name": "Example"
      }
    }
  },
  "Habits.habitsUpdate": {
    "operationId": "habits-update",
    "summary": "Update habit",
    "description": "Update an existing habit",
    "httpMethod": "POST",
    "path": "/habits/update",
    "exampleInput": {
      "body": {
        "id": "item_123",
        "data": {
          "name": "Example",
          "emoji": "string"
        }
      }
    }
  },
  "Habits.habitsDelete": {
    "operationId": "habits-delete",
    "summary": "Delete habit",
    "description": "Delete a habit",
    "httpMethod": "POST",
    "path": "/habits/delete",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "Habits.habitsDuplicate": {
    "operationId": "habits-duplicate",
    "summary": "Duplicate habit",
    "description": "Duplicate an existing habit",
    "httpMethod": "POST",
    "path": "/habits/duplicate",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "Habits.habitsLogHabitOnDay": {
    "operationId": "habits-logHabitOnDay",
    "summary": "Log habit",
    "description": "Log a habit completion or failure for a specific day",
    "httpMethod": "POST",
    "path": "/habits/log",
    "exampleInput": {
      "body": {
        "habitId": "habit_123"
      }
    }
  },
  "Habits.habitsLogManyHabitsOnDay": {
    "operationId": "habits-logManyHabitsOnDay",
    "summary": "Log many habits",
    "description": "Log multiple habits for a specific day",
    "httpMethod": "POST",
    "path": "/habits/log-many",
    "exampleInput": {
      "body": {
        "habitIds": [
          "habit_123"
        ],
        "completionType": "Done"
      }
    }
  },
  "Habits.habitsGetHabitScoreForWidget": {
    "operationId": "habits-getHabitScoreForWidget",
    "summary": "Get habit score for widget",
    "description": "Get aggregated habit score for the widget",
    "httpMethod": "POST",
    "path": "/habits/score/widget"
  },
  "Hydration.hydrationLogsDelete": {
    "operationId": "hydrationLogs-delete",
    "summary": "Delete hydration log",
    "description": "Delete a hydration log",
    "httpMethod": "DELETE",
    "path": "/hydration/logs/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "Hydration.hydrationLogsUpdate": {
    "operationId": "hydrationLogs-update",
    "summary": "Update hydration log",
    "description": "Update an existing hydration log",
    "httpMethod": "PATCH",
    "path": "/hydration/logs/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      },
      "body": {
        "data": {
          "name": "Example",
          "amount": 1
        }
      }
    }
  },
  "Hydration.hydrationLogsGet": {
    "operationId": "hydrationLogs-get",
    "summary": "Get hydration log",
    "description": "Get a single hydration log by ID",
    "httpMethod": "POST",
    "path": "/hydration/logs/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "Hydration.hydrationLogsList": {
    "operationId": "hydrationLogs-list",
    "summary": "List hydration logs",
    "description": "List hydration logs for a date range",
    "httpMethod": "POST",
    "path": "/hydration/logs/list",
    "exampleInput": {
      "body": {
        "date": {
          "year": 1,
          "month": 1,
          "day": 1
        }
      }
    }
  },
  "Hydration.hydrationLogsCreate": {
    "operationId": "hydrationLogs-create",
    "summary": "Create hydration log",
    "description": "Create a new hydration log",
    "httpMethod": "POST",
    "path": "/hydration/logs",
    "exampleInput": {
      "body": {
        "amount": 1
      }
    }
  },
  "Hydration.hydrationLogsDeleteMany": {
    "operationId": "hydrationLogs-deleteMany",
    "summary": "Delete multiple hydration logs",
    "description": "Delete multiple hydration logs",
    "httpMethod": "POST",
    "path": "/hydration/logs/delete-many",
    "exampleInput": {
      "body": {
        "ids": [
          "item_123"
        ]
      }
    }
  },
  "Hydration.hydrationLogsGetStats": {
    "operationId": "hydrationLogs-getStats",
    "summary": "Get hydration stats",
    "description": "Get hydration stats for a date",
    "httpMethod": "POST",
    "path": "/hydration/stats",
    "exampleInput": {
      "body": {
        "date": {
          "year": 1,
          "month": 1,
          "day": 1
        }
      }
    }
  },
  "Hydration.hydrationGoalsDelete": {
    "operationId": "hydrationGoals-delete",
    "summary": "Delete hydration goal",
    "description": "Delete a hydration goal by ID.",
    "httpMethod": "DELETE",
    "path": "/hydration/goals/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "Hydration.hydrationGoalsUpdate": {
    "operationId": "hydrationGoals-update",
    "summary": "Update hydration goal",
    "description": "Update an existing hydration goal.",
    "httpMethod": "PATCH",
    "path": "/hydration/goals/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      },
      "body": {
        "data": {
          "date": {
            "timezone": "Europe/Warsaw",
            "dateInUsersTimezone": "2026-03-30"
          },
          "amount": 1
        }
      }
    }
  },
  "Hydration.hydrationGoalsGet": {
    "operationId": "hydrationGoals-get",
    "summary": "Get hydration goal",
    "description": "Get a single hydration goal by ID.",
    "httpMethod": "POST",
    "path": "/hydration/goals/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "Hydration.hydrationGoalsList": {
    "operationId": "hydrationGoals-list",
    "summary": "List hydration goals",
    "description": "List hydration goals for the current user.",
    "httpMethod": "POST",
    "path": "/hydration/goals/list"
  },
  "Hydration.hydrationGoalsGetForDate": {
    "operationId": "hydrationGoals-getForDate",
    "summary": "Get hydration goal for date",
    "description": "Get the active hydration goal for a date.",
    "httpMethod": "POST",
    "path": "/hydration/goals/for-date",
    "exampleInput": {
      "body": {
        "date": "2026-03-30"
      }
    }
  },
  "Hydration.hydrationGoalsCreate": {
    "operationId": "hydrationGoals-create",
    "summary": "Create hydration goal",
    "description": "Create a new hydration goal for the current user.",
    "httpMethod": "POST",
    "path": "/hydration/goals",
    "exampleInput": {
      "body": {
        "date": {
          "timezone": "Europe/Warsaw",
          "dateInUsersTimezone": "2026-03-30"
        },
        "amount": 1
      }
    }
  },
  "Fasting.fastingDelete": {
    "operationId": "fasting-delete",
    "summary": "Delete fast",
    "description": "Delete a fast",
    "httpMethod": "DELETE",
    "path": "/fasting/fasts/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "Fasting.fastingUpdate": {
    "operationId": "fasting-update",
    "summary": "Update fast",
    "description": "Update an existing fast",
    "httpMethod": "PATCH",
    "path": "/fasting/fasts/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      },
      "body": {
        "data": {
          "goal": 1,
          "startTime": {
            "timezone": "Europe/Warsaw",
            "dateInUsersTimezone": "2026-03-30"
          }
        }
      }
    }
  },
  "Fasting.fastingGet": {
    "operationId": "fasting-get",
    "summary": "Get fast",
    "description": "Get a single fast by ID",
    "httpMethod": "POST",
    "path": "/fasting/fasts/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "Fasting.fastingList": {
    "operationId": "fasting-list",
    "summary": "List fasts",
    "description": "List fasts for a date range",
    "httpMethod": "POST",
    "path": "/fasting/fasts/list",
    "exampleInput": {
      "body": {
        "dateFrom": "2026-03-30",
        "dateTo": "2026-03-30"
      }
    }
  },
  "Fasting.fastingGetActive": {
    "operationId": "fasting-getActive",
    "summary": "Get active fast",
    "description": "Get the currently active fast",
    "httpMethod": "POST",
    "path": "/fasting/active"
  },
  "Fasting.fastingGetStats": {
    "operationId": "fasting-getStats",
    "summary": "Get fasting stats",
    "description": "Get fasting statistics",
    "httpMethod": "POST",
    "path": "/fasting/stats"
  },
  "Fasting.fastingGetDashboardInfo": {
    "operationId": "fasting-getDashboardInfo",
    "summary": "Get dashboard info",
    "description": "Get fasting information for the dashboard",
    "httpMethod": "POST",
    "path": "/fasting/dashboard"
  },
  "Fasting.fastingStart": {
    "operationId": "fasting-start",
    "summary": "Start fast",
    "description": "Start a new fast",
    "httpMethod": "POST",
    "path": "/fasting/start",
    "exampleInput": {
      "body": {
        "hours": 16,
        "startTime": {
          "timezone": "Europe/Warsaw",
          "dateInUsersTimezone": "2026-03-30"
        }
      }
    }
  },
  "Fasting.fastingEnd": {
    "operationId": "fasting-end",
    "summary": "End fast",
    "description": "End an active fast",
    "httpMethod": "POST",
    "path": "/fasting/end",
    "exampleInput": {
      "body": {
        "fastId": "fast_123"
      }
    }
  },
  "Food.foodLogsDelete": {
    "operationId": "foodLogs-delete",
    "summary": "Delete food log",
    "description": "Delete a food log by ID.",
    "httpMethod": "DELETE",
    "path": "/food/logs/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "Food.foodLogsUpdate": {
    "operationId": "foodLogs-update",
    "summary": "Update food log",
    "description": "Update an existing food log.",
    "httpMethod": "PATCH",
    "path": "/food/logs/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      },
      "body": {
        "data": {
          "title": "Example",
          "reasons": [
            "Hungry"
          ]
        }
      }
    }
  },
  "Food.foodLogsGet": {
    "operationId": "foodLogs-get",
    "summary": "Get food log",
    "description": "Get a single food log by ID.",
    "httpMethod": "POST",
    "path": "/food/logs/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "Food.foodLogsList": {
    "operationId": "foodLogs-list",
    "summary": "List food logs",
    "description": "List food logs for a date range.",
    "httpMethod": "POST",
    "path": "/food/logs/list",
    "exampleInput": {
      "body": {
        "date": {
          "year": 1,
          "month": 1,
          "day": 1
        }
      }
    }
  },
  "Food.foodLogsCreate": {
    "operationId": "foodLogs-create",
    "summary": "Create food log",
    "description": "Create a new food log.",
    "httpMethod": "POST",
    "path": "/food/logs",
    "exampleInput": {
      "body": {
        "portionSize": 1,
        "healthiness": 1
      }
    }
  },
  "Food.foodLogsDeleteMany": {
    "operationId": "foodLogs-deleteMany",
    "summary": "Delete multiple food logs",
    "description": "Delete multiple food logs by ID.",
    "httpMethod": "POST",
    "path": "/food/logs/delete-many",
    "exampleInput": {
      "body": {
        "ids": [
          "item_123"
        ]
      }
    }
  },
  "Food.foodLogsGetCaloriesStats": {
    "operationId": "foodLogs-getCaloriesStats",
    "summary": "Get food calories stats",
    "description": "Get total calories and calorie goal stats for a date.",
    "httpMethod": "POST",
    "path": "/food/stats/calories",
    "exampleInput": {
      "body": {
        "date": {
          "year": 1,
          "month": 1,
          "day": 1
        }
      }
    }
  },
  "Food.foodLogsGetProteinStats": {
    "operationId": "foodLogs-getProteinStats",
    "summary": "Get food protein stats",
    "description": "Get total protein and protein goal stats for a date.",
    "httpMethod": "POST",
    "path": "/food/stats/protein",
    "exampleInput": {
      "body": {
        "date": {
          "year": 1,
          "month": 1,
          "day": 1
        }
      }
    }
  },
  "Food.foodLogsGetCarbsStats": {
    "operationId": "foodLogs-getCarbsStats",
    "summary": "Get food carbs stats",
    "description": "Get total carbs and carbs goal stats for a date.",
    "httpMethod": "POST",
    "path": "/food/stats/carbs",
    "exampleInput": {
      "body": {
        "date": {
          "year": 1,
          "month": 1,
          "day": 1
        }
      }
    }
  },
  "WeightLogs.weightLogsGet": {
    "operationId": "weightLogs-get",
    "summary": "Get weight log",
    "description": "Get a single weight log by ID.",
    "httpMethod": "POST",
    "path": "/weight-logs/get",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "WeightLogs.weightLogsList": {
    "operationId": "weightLogs-list",
    "summary": "List weight logs",
    "description": "Get weight logs for the user, optionally filtered by date range.",
    "httpMethod": "POST",
    "path": "/weight-logs/list",
    "exampleInput": {
      "body": {
        "date": "2026-03-30",
        "dateFrom": "2026-03-30"
      }
    }
  },
  "WeightLogs.weightLogsCreate": {
    "operationId": "weightLogs-create",
    "summary": "Create weight log",
    "description": "Create a new weight log entry.",
    "httpMethod": "POST",
    "path": "/weight-logs/create",
    "exampleInput": {
      "body": {
        "weight": 1,
        "fatPercentage": 1,
        "musclePercentage": 1
      }
    }
  },
  "WeightLogs.weightLogsUpdate": {
    "operationId": "weightLogs-update",
    "summary": "Update weight log",
    "description": "Update an existing weight log.",
    "httpMethod": "POST",
    "path": "/weight-logs/update",
    "exampleInput": {
      "body": {
        "id": "item_123",
        "data": {
          "weight": 1,
          "fatPercentage": 1
        }
      }
    }
  },
  "WeightLogs.weightLogsDelete": {
    "operationId": "weightLogs-delete",
    "summary": "Delete weight log",
    "description": "Delete a weight log by ID.",
    "httpMethod": "POST",
    "path": "/weight-logs/delete",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "WeightLogs.weightLogsDeleteMany": {
    "operationId": "weightLogs-deleteMany",
    "summary": "Delete many weight logs",
    "description": "Delete multiple weight log entries.",
    "httpMethod": "POST",
    "path": "/weight-logs/delete-many",
    "exampleInput": {
      "body": {
        "ids": [
          "item_123"
        ]
      }
    }
  },
  "WeightLogs.weightLogsGetSettings": {
    "operationId": "weightLogs-getSettings",
    "summary": "Get weight settings",
    "description": "Get user weight unit preferences.",
    "httpMethod": "POST",
    "path": "/weight-logs/settings/get"
  },
  "WeightLogs.weightLogsUpdateWeightUnit": {
    "operationId": "weightLogs-updateWeightUnit",
    "summary": "Update weight settings",
    "description": "Update user weight unit preference.",
    "httpMethod": "POST",
    "path": "/weight-logs/settings/update",
    "exampleInput": {
      "body": {
        "weightUnit": "kg"
      }
    }
  },
  "WeightLogs.weightLogsGetWeightsForWidget": {
    "operationId": "weightLogs-getWeightsForWidget",
    "summary": "Get weights for widget",
    "description": "Get recent weight data points for widget charts.",
    "httpMethod": "POST",
    "path": "/weight-logs/widget"
  },
  "WeightLogs.weightLogsGetCurrentActiveGoal": {
    "operationId": "weightLogs-getCurrentActiveGoal",
    "summary": "Get current weight goal",
    "description": "Get the active weight goal with start and current weight context.",
    "httpMethod": "POST",
    "path": "/weight-logs/current-goal"
  },
  "Workouts.workoutsDelete": {
    "operationId": "workouts-delete",
    "summary": "Delete workout",
    "description": "Delete a workout",
    "httpMethod": "DELETE",
    "path": "/workouts/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "Workouts.workoutsUpdate": {
    "operationId": "workouts-update",
    "summary": "Update workout",
    "description": "Update an existing workout",
    "httpMethod": "PATCH",
    "path": "/workouts/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      },
      "body": {
        "data": {
          "name": "Example",
          "startedAt": {
            "timezone": "Europe/Warsaw",
            "dateInUsersTimezone": "2026-03-30"
          }
        }
      }
    }
  },
  "Workouts.workoutsGet": {
    "operationId": "workouts-get",
    "summary": "Get workout",
    "description": "Get a single workout by ID",
    "httpMethod": "POST",
    "path": "/workouts/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "Workouts.workoutsList": {
    "operationId": "workouts-list",
    "summary": "List workouts",
    "description": "List workouts for a date range",
    "httpMethod": "POST",
    "path": "/workouts/list",
    "exampleInput": {
      "body": {
        "dateFrom": "2026-03-30",
        "dateTo": "2026-03-30"
      }
    }
  },
  "Workouts.workoutsCreate": {
    "operationId": "workouts-create",
    "summary": "Create workout",
    "description": "Create a new workout",
    "httpMethod": "POST",
    "path": "/workouts",
    "exampleInput": {
      "body": {
        "name": "Example",
        "startedAt": {
          "timezone": "Europe/Warsaw",
          "dateInUsersTimezone": "2026-03-30"
        }
      }
    }
  },
  "Workouts.workoutsInProgress": {
    "operationId": "workouts-inProgress",
    "summary": "Get in-progress workout",
    "description": "Get the currently in-progress workout",
    "httpMethod": "POST",
    "path": "/workouts/in-progress"
  },
  "Workouts.workoutsStart": {
    "operationId": "workouts-start",
    "summary": "Start workout",
    "description": "Start a new workout",
    "httpMethod": "POST",
    "path": "/workouts/start",
    "exampleInput": {
      "body": {
        "name": "Example"
      }
    }
  },
  "Workouts.workoutsEnd": {
    "operationId": "workouts-end",
    "summary": "End workout",
    "description": "End an in-progress workout",
    "httpMethod": "POST",
    "path": "/workouts/end",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "Workouts.workoutsDuplicate": {
    "operationId": "workouts-duplicate",
    "summary": "Duplicate workout",
    "description": "Duplicate an existing workout",
    "httpMethod": "POST",
    "path": "/workouts/{id}/duplicate",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "Workouts.workoutsGetWithDetails": {
    "operationId": "workouts-getWithDetails",
    "summary": "Get workout with details",
    "description": "Get a workout with full details (exercises, sets)",
    "httpMethod": "POST",
    "path": "/workouts/{id}/details",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "Workouts.workoutsUpdateName": {
    "operationId": "workouts-updateName",
    "summary": "Update workout name",
    "description": "Update the name of a workout",
    "httpMethod": "PATCH",
    "path": "/workouts/{id}/name",
    "exampleInput": {
      "path": {
        "id": "item_123"
      },
      "body": {
        "name": "Example"
      }
    }
  },
  "Workouts.workoutsActiveUsers": {
    "operationId": "workouts-activeUsers",
    "summary": "Get active users",
    "description": "Get users who are currently working out",
    "httpMethod": "POST",
    "path": "/workouts/active-users"
  },
  "Workouts.workoutsSubmitComplete": {
    "operationId": "workouts-submitComplete",
    "summary": "Submit complete workout",
    "description": "Submit a complete workout with all exercises and sets",
    "httpMethod": "POST",
    "path": "/workouts/submit-complete",
    "exampleInput": {
      "body": {
        "name": "Example",
        "startedAt": "string",
        "endedAt": "string"
      }
    }
  },
  "Journal.journalEntriesList": {
    "operationId": "journalEntries-list",
    "summary": "List journal entries",
    "description": "List journal entries for a date range",
    "httpMethod": "POST",
    "path": "/journal/entries/list",
    "exampleInput": {
      "body": {
        "encryptionKey": "string",
        "dateFrom": "2026-03-30"
      }
    }
  },
  "Journal.journalEntriesStats": {
    "operationId": "journalEntries-stats",
    "summary": "Get journal stats",
    "description": "Get statistics for journal entries",
    "httpMethod": "POST",
    "path": "/journal/stats",
    "exampleInput": {
      "body": {
        "encryptionKey": "string"
      }
    }
  },
  "Journal.journalEntriesDelete": {
    "operationId": "journalEntries-delete",
    "summary": "Delete journal entry",
    "description": "Delete a journal entry",
    "httpMethod": "DELETE",
    "path": "/journal/entries/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "Journal.journalEntriesUpdate": {
    "operationId": "journalEntries-update",
    "summary": "Update journal entry",
    "description": "Update an existing journal entry",
    "httpMethod": "PATCH",
    "path": "/journal/entries/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      },
      "body": {
        "data": {
          "title": "Example",
          "content": "Example"
        }
      }
    }
  },
  "Journal.journalEntriesGet": {
    "operationId": "journalEntries-get",
    "summary": "Get journal entry",
    "description": "Get a single journal entry",
    "httpMethod": "POST",
    "path": "/journal/entries/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      },
      "body": {
        "encryptionKey": "string"
      }
    }
  },
  "Journal.journalEntriesGetForDecrypting": {
    "operationId": "journalEntries-getForDecrypting",
    "summary": "Get entry for decrypting",
    "description": "Get entry for decrypting without persisting changes",
    "httpMethod": "POST",
    "path": "/journal/entries/{id}/decrypt-preview",
    "exampleInput": {
      "path": {
        "id": "item_123"
      },
      "body": {
        "encryptionKey": "string"
      }
    }
  },
  "Journal.journalEntriesCreate": {
    "operationId": "journalEntries-create",
    "summary": "Create journal entry",
    "description": "Create a new journal entry",
    "httpMethod": "POST",
    "path": "/journal/entries",
    "exampleInput": {
      "body": {
        "content": "Example"
      }
    }
  },
  "Journal.journalEntriesDeleteMany": {
    "operationId": "journalEntries-deleteMany",
    "summary": "Delete multiple entries",
    "description": "Delete multiple journal entries",
    "httpMethod": "POST",
    "path": "/journal/entries/delete-many",
    "exampleInput": {
      "body": {
        "ids": [
          "item_123"
        ]
      }
    }
  },
  "Journal.journalEntriesUpdateManyEncryption": {
    "operationId": "journalEntries-updateManyEncryption",
    "summary": "Update encryption status",
    "description": "Update encryption status for multiple entries",
    "httpMethod": "POST",
    "path": "/journal/entries/update-many-encryption",
    "exampleInput": {
      "body": {
        "ids": [
          "item_123"
        ],
        "encrypted": true
      }
    }
  },
  "Journal.journalEntriesEncryptMany": {
    "operationId": "journalEntries-encryptMany",
    "summary": "Encrypt multiple entries",
    "description": "Encrypt multiple journal entries",
    "httpMethod": "POST",
    "path": "/journal/entries/encrypt-many",
    "exampleInput": {
      "body": {
        "ids": [
          "item_123"
        ],
        "encryptionKey": "string"
      }
    }
  },
  "Journal.journalEntriesEncrypt": {
    "operationId": "journalEntries-encrypt",
    "summary": "Encrypt entry",
    "description": "Encrypt a single journal entry",
    "httpMethod": "POST",
    "path": "/journal/entries/{id}/encrypt",
    "exampleInput": {
      "path": {
        "id": "item_123"
      },
      "body": {
        "encryptionKey": "string"
      }
    }
  },
  "Journal.journalEntriesDecrypt": {
    "operationId": "journalEntries-decrypt",
    "summary": "Decrypt entry",
    "description": "Permanently decrypt a journal entry",
    "httpMethod": "POST",
    "path": "/journal/entries/{id}/decrypt",
    "exampleInput": {
      "path": {
        "id": "item_123"
      },
      "body": {
        "encryptionKey": "string"
      }
    }
  },
  "Journal.journalEntriesToggleEncryption": {
    "operationId": "journalEntries-toggleEncryption",
    "summary": "Toggle encryption flag",
    "description": "Toggle encryption flag without processing content",
    "httpMethod": "POST",
    "path": "/journal/entries/{id}/toggle-encryption",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "PlannerEventLists.plannerEventListsList": {
    "operationId": "plannerEventLists-list",
    "summary": "List planner event lists",
    "description": "List planner event lists for the current user",
    "httpMethod": "POST",
    "path": "/planner-event-lists/list"
  },
  "PlannerEventLists.plannerEventListsHasSharedLists": {
    "operationId": "plannerEventLists-hasSharedLists",
    "summary": "Check if user has shared planner event lists",
    "description": "Returns whether the current user has planner event lists shared with them",
    "httpMethod": "POST",
    "path": "/planner-event-lists/has-shared-lists"
  },
  "PlannerEventLists.plannerEventListsDelete": {
    "operationId": "plannerEventLists-delete",
    "summary": "Delete planner event list",
    "description": "Delete a planner event list",
    "httpMethod": "DELETE",
    "path": "/planner-event-lists/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "PlannerEventLists.plannerEventListsUpdate": {
    "operationId": "plannerEventLists-update",
    "summary": "Update planner event list",
    "description": "Update an existing planner event list",
    "httpMethod": "PATCH",
    "path": "/planner-event-lists/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      },
      "body": {
        "data": {
          "name": "Example",
          "emoji": "string"
        }
      }
    }
  },
  "PlannerEventLists.plannerEventListsGet": {
    "operationId": "plannerEventLists-get",
    "summary": "Get planner event list",
    "description": "Get a single planner event list by ID",
    "httpMethod": "POST",
    "path": "/planner-event-lists/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "PlannerEventLists.plannerEventListsCreate": {
    "operationId": "plannerEventLists-create",
    "summary": "Create planner event list",
    "description": "Create a new planner event list",
    "httpMethod": "POST",
    "path": "/planner-event-lists",
    "exampleInput": {
      "body": {
        "name": "Example"
      }
    }
  },
  "TodoViews.todoViewsDone": {
    "operationId": "todoViews-done",
    "summary": "List completed todos",
    "description": "List completed todos for the current user.",
    "httpMethod": "POST",
    "path": "/todo-views/done",
    "exampleInput": {
      "body": {
        "taskType": "personal"
      }
    }
  },
  "TodoViews.todoViewsTrash": {
    "operationId": "todoViews-trash",
    "summary": "List trashed todos",
    "description": "List deleted todos for the current user.",
    "httpMethod": "POST",
    "path": "/todo-views/trash",
    "exampleInput": {
      "body": {
        "skip": 1,
        "take": 1
      }
    }
  },
  "TodoViews.todoViewsPaused": {
    "operationId": "todoViews-paused",
    "summary": "List paused todos",
    "description": "List paused todos for the current user.",
    "httpMethod": "POST",
    "path": "/todo-views/paused",
    "exampleInput": {
      "body": {
        "taskType": "personal"
      }
    }
  },
  "TodoViews.todoViewsRecurring": {
    "operationId": "todoViews-recurring",
    "summary": "List recurring todos",
    "description": "List recurring todos for the current user.",
    "httpMethod": "POST",
    "path": "/todo-views/recurring",
    "exampleInput": {
      "body": {
        "taskType": "personal"
      }
    }
  },
  "TodoViews.todoViewsSharing": {
    "operationId": "todoViews-sharing",
    "summary": "Get todo list sharing info",
    "description": "Get sharing details for a todo list visible to the current user.",
    "httpMethod": "POST",
    "path": "/todo-views/sharing",
    "exampleInput": {
      "body": {
        "listId": "list_123"
      }
    }
  },
  "ProjectSections.projectSectionsDelete": {
    "operationId": "projectSections-delete",
    "summary": "Delete project section",
    "description": "Delete a project section and optionally its todos.",
    "httpMethod": "DELETE",
    "path": "/project-sections/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      },
      "query": {
        "deleteTodos": true
      }
    }
  },
  "ProjectSections.projectSectionsUpdate": {
    "operationId": "projectSections-update",
    "summary": "Update project section",
    "description": "Update a project section visible to the current user.",
    "httpMethod": "PATCH",
    "path": "/project-sections/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      },
      "body": {
        "data": {
          "name": "Example"
        }
      }
    }
  },
  "TodoListSections.todoListSectionsDelete": {
    "operationId": "todoListSections-delete",
    "summary": "Delete todo list section",
    "description": "Delete a todo list section and optionally its todos.",
    "httpMethod": "DELETE",
    "path": "/todo-list-sections/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      },
      "query": {
        "deleteTodos": true
      }
    }
  },
  "TodoListSections.todoListSectionsUpdate": {
    "operationId": "todoListSections-update",
    "summary": "Update todo list section",
    "description": "Update a todo list section visible to the current user.",
    "httpMethod": "PATCH",
    "path": "/todo-list-sections/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      },
      "body": {
        "data": {
          "name": "Example"
        }
      }
    }
  },
  "Countdowns.countdownsList": {
    "operationId": "countdowns-list",
    "summary": "List countdowns",
    "description": "List countdowns for the current user",
    "httpMethod": "POST",
    "path": "/countdowns/list"
  },
  "Countdowns.countdownsDelete": {
    "operationId": "countdowns-delete",
    "summary": "Delete countdown",
    "description": "Delete a countdown",
    "httpMethod": "DELETE",
    "path": "/countdowns/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "Countdowns.countdownsUpdate": {
    "operationId": "countdowns-update",
    "summary": "Update countdown",
    "description": "Update an existing countdown",
    "httpMethod": "PATCH",
    "path": "/countdowns/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      },
      "body": {
        "data": {
          "title": "Example",
          "emoji": "string"
        }
      }
    }
  },
  "Countdowns.countdownsGet": {
    "operationId": "countdowns-get",
    "summary": "Get countdown",
    "description": "Get a single countdown by ID",
    "httpMethod": "POST",
    "path": "/countdowns/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "Countdowns.countdownsCreate": {
    "operationId": "countdowns-create",
    "summary": "Create countdown",
    "description": "Create a new countdown",
    "httpMethod": "POST",
    "path": "/countdowns",
    "exampleInput": {
      "body": {
        "title": "Example",
        "emoji": "string"
      }
    }
  },
  "Locations.locationsDelete": {
    "operationId": "locations-delete",
    "summary": "Delete location",
    "description": "Delete a location by ID.",
    "httpMethod": "DELETE",
    "path": "/locations/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "Locations.locationsUpdate": {
    "operationId": "locations-update",
    "summary": "Update location",
    "description": "Update an existing location.",
    "httpMethod": "PATCH",
    "path": "/locations/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      },
      "body": {
        "data": {
          "name": "Example",
          "emoji": "string"
        }
      }
    }
  },
  "Locations.locationsGet": {
    "operationId": "locations-get",
    "summary": "Get location",
    "description": "Get a single location by ID.",
    "httpMethod": "POST",
    "path": "/locations/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "Locations.locationsList": {
    "operationId": "locations-list",
    "summary": "List locations",
    "description": "List locations for the current user.",
    "httpMethod": "POST",
    "path": "/locations/list",
    "exampleInput": {
      "body": {}
    }
  },
  "Locations.locationsCreate": {
    "operationId": "locations-create",
    "summary": "Create location",
    "description": "Create a new location.",
    "httpMethod": "POST",
    "path": "/locations",
    "exampleInput": {
      "body": {
        "name": "Example"
      }
    }
  },
  "Goals.goalsDelete": {
    "operationId": "goals-delete",
    "summary": "Delete goal",
    "description": "Delete a goal.",
    "httpMethod": "DELETE",
    "path": "/goals/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "Goals.goalsUpdate": {
    "operationId": "goals-update",
    "summary": "Update goal",
    "description": "Update an existing goal.",
    "httpMethod": "PATCH",
    "path": "/goals/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      },
      "body": {
        "data": {
          "name": "Example",
          "dueDate": {
            "timezone": "Europe/Warsaw",
            "dateInUsersTimezone": "2026-03-30"
          }
        }
      }
    }
  },
  "Goals.goalsGet": {
    "operationId": "goals-get",
    "summary": "Get goal",
    "description": "Fetch a goal by id.",
    "httpMethod": "POST",
    "path": "/goals/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "Goals.goalsList": {
    "operationId": "goals-list",
    "summary": "List goals",
    "description": "List all goals for the current user.",
    "httpMethod": "POST",
    "path": "/goals/list"
  },
  "Goals.goalsPublicList": {
    "operationId": "goals-publicList",
    "summary": "List public goals",
    "description": "List public goals for a user by username.",
    "httpMethod": "POST",
    "path": "/goals/public/{username}",
    "exampleInput": {
      "path": {
        "username": "Example"
      }
    }
  },
  "Goals.goalsCreate": {
    "operationId": "goals-create",
    "summary": "Create goal",
    "description": "Create a new goal.",
    "httpMethod": "POST",
    "path": "/goals",
    "exampleInput": {
      "body": {
        "name": "Example"
      }
    }
  },
  "Goals.goalsDeleteMany": {
    "operationId": "goals-deleteMany",
    "summary": "Delete many goals",
    "description": "Delete multiple goals by ids.",
    "httpMethod": "POST",
    "path": "/goals/delete-many",
    "exampleInput": {
      "body": {
        "ids": [
          "item_123"
        ]
      }
    }
  },
  "BloodPressureLogs.bloodPressureLogsList": {
    "operationId": "bloodPressureLogs-list",
    "summary": "List blood pressure logs",
    "description": "Get blood pressure logs for the current user, optionally filtered by date range.",
    "httpMethod": "POST",
    "path": "/blood-pressure-logs/list",
    "exampleInput": {
      "body": {
        "dateFrom": "2026-03-30",
        "dateTo": "2026-03-30"
      }
    }
  },
  "BloodPressureLogs.bloodPressureLogsGet": {
    "operationId": "bloodPressureLogs-get",
    "summary": "Get blood pressure log",
    "description": "Get a single blood pressure log by ID.",
    "httpMethod": "POST",
    "path": "/blood-pressure-logs/get",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "BloodPressureLogs.bloodPressureLogsCreate": {
    "operationId": "bloodPressureLogs-create",
    "summary": "Create blood pressure log",
    "description": "Create a new blood pressure log entry.",
    "httpMethod": "POST",
    "path": "/blood-pressure-logs/create",
    "exampleInput": {
      "body": {
        "systolic": 1,
        "diastolic": 1
      }
    }
  },
  "BloodPressureLogs.bloodPressureLogsUpdate": {
    "operationId": "bloodPressureLogs-update",
    "summary": "Update blood pressure log",
    "description": "Update an existing blood pressure log.",
    "httpMethod": "POST",
    "path": "/blood-pressure-logs/update",
    "exampleInput": {
      "body": {
        "id": "item_123",
        "data": {
          "systolic": 1,
          "diastolic": 1
        }
      }
    }
  },
  "BloodPressureLogs.bloodPressureLogsDelete": {
    "operationId": "bloodPressureLogs-delete",
    "summary": "Delete blood pressure log",
    "description": "Delete a blood pressure log by ID.",
    "httpMethod": "POST",
    "path": "/blood-pressure-logs/delete",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "BloodPressureLogs.bloodPressureLogsDeleteMany": {
    "operationId": "bloodPressureLogs-deleteMany",
    "summary": "Delete multiple blood pressure logs",
    "description": "Delete blood pressure logs in bulk.",
    "httpMethod": "POST",
    "path": "/blood-pressure-logs/delete-many",
    "exampleInput": {
      "body": {
        "ids": [
          "item_123"
        ]
      }
    }
  },
  "HydrationTemplates.hydrationTemplatesGet": {
    "operationId": "hydrationTemplates-get",
    "summary": "Get hydration template",
    "description": "Get a single hydration template by ID.",
    "httpMethod": "POST",
    "path": "/hydration-templates/get",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "HydrationTemplates.hydrationTemplatesList": {
    "operationId": "hydrationTemplates-list",
    "summary": "List hydration templates",
    "description": "List hydration templates for the current user.",
    "httpMethod": "POST",
    "path": "/hydration-templates/list"
  },
  "HydrationTemplates.hydrationTemplatesCreate": {
    "operationId": "hydrationTemplates-create",
    "summary": "Create hydration template",
    "description": "Create a new hydration template.",
    "httpMethod": "POST",
    "path": "/hydration-templates",
    "exampleInput": {
      "body": {
        "name": "Example",
        "amount": 1,
        "type": "Water"
      }
    }
  },
  "HydrationTemplates.hydrationTemplatesUpdate": {
    "operationId": "hydrationTemplates-update",
    "summary": "Update hydration template",
    "description": "Update an existing hydration template.",
    "httpMethod": "PATCH",
    "path": "/hydration-templates/update",
    "exampleInput": {
      "body": {
        "id": "item_123",
        "data": {
          "name": "Example",
          "amount": 1
        }
      }
    }
  },
  "HydrationTemplates.hydrationTemplatesDelete": {
    "operationId": "hydrationTemplates-delete",
    "summary": "Delete hydration template",
    "description": "Delete a hydration template.",
    "httpMethod": "DELETE",
    "path": "/hydration-templates/delete",
    "exampleInput": {
      "query": {
        "id": "item_123"
      }
    }
  },
  "HydrationTemplates.hydrationTemplatesDeleteMany": {
    "operationId": "hydrationTemplates-deleteMany",
    "summary": "Delete multiple hydration templates",
    "description": "Delete multiple hydration templates.",
    "httpMethod": "POST",
    "path": "/hydration-templates/delete-many",
    "exampleInput": {
      "body": {
        "ids": [
          "item_123"
        ]
      }
    }
  },
  "FoodTemplates.foodTemplatesGet": {
    "operationId": "foodTemplates-get",
    "summary": "Get food template",
    "description": "Get a single food template by ID.",
    "httpMethod": "POST",
    "path": "/food-templates/get",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "FoodTemplates.foodTemplatesList": {
    "operationId": "foodTemplates-list",
    "summary": "List food templates",
    "description": "List food templates for the current user.",
    "httpMethod": "POST",
    "path": "/food-templates/list"
  },
  "FoodTemplates.foodTemplatesCreate": {
    "operationId": "foodTemplates-create",
    "summary": "Create food template",
    "description": "Create a new food template.",
    "httpMethod": "POST",
    "path": "/food-templates",
    "exampleInput": {
      "body": {
        "title": "Example"
      }
    }
  },
  "FoodTemplates.foodTemplatesUpdate": {
    "operationId": "foodTemplates-update",
    "summary": "Update food template",
    "description": "Update an existing food template.",
    "httpMethod": "PATCH",
    "path": "/food-templates/update",
    "exampleInput": {
      "body": {
        "id": "item_123",
        "data": {
          "title": "Example",
          "shortName": "Example"
        }
      }
    }
  },
  "FoodTemplates.foodTemplatesDelete": {
    "operationId": "foodTemplates-delete",
    "summary": "Delete food template",
    "description": "Delete a food template.",
    "httpMethod": "DELETE",
    "path": "/food-templates/delete",
    "exampleInput": {
      "query": {
        "id": "item_123"
      }
    }
  },
  "FoodTemplates.foodTemplatesDeleteMany": {
    "operationId": "foodTemplates-deleteMany",
    "summary": "Delete multiple food templates",
    "description": "Delete multiple food templates.",
    "httpMethod": "POST",
    "path": "/food-templates/delete-many",
    "exampleInput": {
      "body": {
        "ids": [
          "item_123"
        ]
      }
    }
  },
  "IngredientLists.ingredientListsList": {
    "operationId": "ingredientLists-list",
    "summary": "List ingredient lists",
    "description": "List ingredient lists visible to the current user.",
    "httpMethod": "POST",
    "path": "/ingredient-lists/list"
  },
  "IngredientLists.ingredientListsDelete": {
    "operationId": "ingredientLists-delete",
    "summary": "Delete ingredient list",
    "description": "Delete a single ingredient list.",
    "httpMethod": "DELETE",
    "path": "/ingredient-lists/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "IngredientLists.ingredientListsUpdate": {
    "operationId": "ingredientLists-update",
    "summary": "Update ingredient list",
    "description": "Update an existing ingredient list.",
    "httpMethod": "PATCH",
    "path": "/ingredient-lists/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      },
      "body": {
        "data": {
          "name": "Example",
          "emoji": "string"
        }
      }
    }
  },
  "IngredientLists.ingredientListsGet": {
    "operationId": "ingredientLists-get",
    "summary": "Get ingredient list",
    "description": "Get a single ingredient list by ID.",
    "httpMethod": "POST",
    "path": "/ingredient-lists/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "IngredientLists.ingredientListsCreate": {
    "operationId": "ingredientLists-create",
    "summary": "Create ingredient list",
    "description": "Create a new ingredient list.",
    "httpMethod": "POST",
    "path": "/ingredient-lists",
    "exampleInput": {
      "body": {
        "name": "Example"
      }
    }
  },
  "IngredientLists.ingredientListsDeleteMany": {
    "operationId": "ingredientLists-deleteMany",
    "summary": "Delete many ingredient lists",
    "description": "Delete multiple ingredient lists visible to the current user.",
    "httpMethod": "POST",
    "path": "/ingredient-lists/delete-many",
    "exampleInput": {
      "body": {
        "ids": [
          "item_123"
        ]
      }
    }
  },
  "MealPlans.mealPlansDelete": {
    "operationId": "mealPlans-delete",
    "summary": "Delete meal plan",
    "description": "Delete a meal plan",
    "httpMethod": "DELETE",
    "path": "/meal-plans/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "MealPlans.mealPlansUpdate": {
    "operationId": "mealPlans-update",
    "summary": "Update meal plan",
    "description": "Update an existing meal plan",
    "httpMethod": "PATCH",
    "path": "/meal-plans/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      },
      "body": {
        "data": {
          "name": "Example",
          "emoji": "string"
        }
      }
    }
  },
  "MealPlans.mealPlansGet": {
    "operationId": "mealPlans-get",
    "summary": "Get meal plan",
    "description": "Get a single meal plan by ID",
    "httpMethod": "POST",
    "path": "/meal-plans/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "MealPlans.mealPlansList": {
    "operationId": "mealPlans-list",
    "summary": "List meal plans",
    "description": "List meal plans for current user",
    "httpMethod": "POST",
    "path": "/meal-plans/list"
  },
  "MealPlans.mealPlansCreate": {
    "operationId": "mealPlans-create",
    "summary": "Create meal plan",
    "description": "Create a new meal plan",
    "httpMethod": "POST",
    "path": "/meal-plans",
    "exampleInput": {
      "body": {
        "name": "Example",
        "emoji": "string"
      }
    }
  },
  "MealPlans.mealPlansDeleteMany": {
    "operationId": "mealPlans-deleteMany",
    "summary": "Delete many meal plans",
    "description": "Delete multiple meal plans",
    "httpMethod": "POST",
    "path": "/meal-plans/delete-many",
    "exampleInput": {
      "body": {
        "ids": [
          "item_123"
        ]
      }
    }
  },
  "Contacts.contactsList": {
    "operationId": "contacts-list",
    "summary": "List contact relationships",
    "description": "List all contact relationships for the current user, ordered by activity.",
    "httpMethod": "POST",
    "path": "/contacts/list",
    "exampleInput": {
      "body": {}
    }
  },
  "Contacts.contactsGet": {
    "operationId": "contacts-get",
    "summary": "Get a contact relationship",
    "description": "Get a single contact relationship by id for the current user.",
    "httpMethod": "POST",
    "path": "/contacts/get",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "Contacts.contactsCreate": {
    "operationId": "contacts-create",
    "summary": "Create a contact relationship",
    "description": "Create a new contact (or update an existing one) and relationship entry.",
    "httpMethod": "POST",
    "path": "/contacts/create",
    "exampleInput": {
      "body": {
        "name": "Example"
      }
    }
  },
  "Contacts.contactsUpdate": {
    "operationId": "contacts-update",
    "summary": "Update a contact relationship",
    "description": "Update relationship metadata and contact fields.",
    "httpMethod": "POST",
    "path": "/contacts/update",
    "exampleInput": {
      "body": {
        "id": "item_123",
        "data": {
          "contactId": "contact_123",
          "name": "Example"
        }
      }
    }
  },
  "Contacts.contactsDelete": {
    "operationId": "contacts-delete",
    "summary": "Delete a contact relationship",
    "description": "Delete a single user contact relationship.",
    "httpMethod": "POST",
    "path": "/contacts/delete",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "Contacts.contactsDeleteMany": {
    "operationId": "contacts-deleteMany",
    "summary": "Delete multiple contact relationships",
    "description": "Delete multiple user contact relationships.",
    "httpMethod": "POST",
    "path": "/contacts/delete-many",
    "exampleInput": {
      "body": {
        "ids": [
          "item_123"
        ]
      }
    }
  },
  "WeightGoals.weightGoalsDelete": {
    "operationId": "weightGoals-delete",
    "summary": "Delete weight goal",
    "description": "Delete a weight goal by ID.",
    "httpMethod": "DELETE",
    "path": "/weight/goals/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "WeightGoals.weightGoalsUpdate": {
    "operationId": "weightGoals-update",
    "summary": "Update weight goal",
    "description": "Update an existing weight goal.",
    "httpMethod": "PATCH",
    "path": "/weight/goals/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      },
      "body": {
        "data": {
          "amount": 1,
          "startsOn": {
            "timezone": "Europe/Warsaw",
            "dateInUsersTimezone": "2026-03-30"
          }
        }
      }
    }
  },
  "WeightGoals.weightGoalsGet": {
    "operationId": "weightGoals-get",
    "summary": "Get weight goal",
    "description": "Get a single weight goal by ID.",
    "httpMethod": "POST",
    "path": "/weight/goals/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "WeightGoals.weightGoalsList": {
    "operationId": "weightGoals-list",
    "summary": "List weight goals",
    "description": "List weight goals for the current user.",
    "httpMethod": "POST",
    "path": "/weight/goals/list"
  },
  "WeightGoals.weightGoalsCreate": {
    "operationId": "weightGoals-create",
    "summary": "Create weight goal",
    "description": "Create a new weight goal.",
    "httpMethod": "POST",
    "path": "/weight/goals",
    "exampleInput": {
      "body": {
        "amount": 1,
        "startsOn": {
          "timezone": "Europe/Warsaw",
          "dateInUsersTimezone": "2026-03-30"
        }
      }
    }
  },
  "WeightGoals.weightGoalsDeleteMany": {
    "operationId": "weightGoals-deleteMany",
    "summary": "Delete multiple weight goals",
    "description": "Delete multiple weight goals by ID.",
    "httpMethod": "POST",
    "path": "/weight/goals/delete-many",
    "exampleInput": {
      "body": {
        "ids": [
          "item_123"
        ]
      }
    }
  },
  "WeightGoals.weightGoalsGetForDate": {
    "operationId": "weightGoals-getForDate",
    "summary": "Get weight goal for date",
    "description": "Get the active weight goal for a date.",
    "httpMethod": "POST",
    "path": "/weight/goals/for-date",
    "exampleInput": {
      "body": {
        "date": "2026-03-30"
      }
    }
  },
  "Problems.problemsList": {
    "operationId": "problems-list",
    "summary": "List problems",
    "description": "List all problems for the current user.",
    "httpMethod": "GET",
    "path": "/problems"
  },
  "Problems.problemsCreate": {
    "operationId": "problems-create",
    "summary": "Create problem",
    "description": "Create a new problem.",
    "httpMethod": "POST",
    "path": "/problems",
    "exampleInput": {
      "body": {
        "name": "Example"
      }
    }
  },
  "Problems.problemsDelete": {
    "operationId": "problems-delete",
    "summary": "Delete problem",
    "description": "Delete a problem and all related logs.",
    "httpMethod": "DELETE",
    "path": "/problems/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "Problems.problemsGet": {
    "operationId": "problems-get",
    "summary": "Get problem",
    "description": "Fetch a problem by id.",
    "httpMethod": "GET",
    "path": "/problems/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "Problems.problemsUpdate": {
    "operationId": "problems-update",
    "summary": "Update problem",
    "description": "Update an existing problem.",
    "httpMethod": "PATCH",
    "path": "/problems/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      },
      "body": {
        "data": {
          "name": "Example",
          "emoji": "string"
        }
      }
    }
  },
  "Problems.problemsDeleteMany": {
    "operationId": "problems-deleteMany",
    "summary": "Delete many problems",
    "description": "Delete multiple problems.",
    "httpMethod": "POST",
    "path": "/problems/delete-many",
    "exampleInput": {
      "body": {
        "ids": [
          "item_123"
        ]
      }
    }
  },
  "Problems.problemsListLogs": {
    "operationId": "problems-listLogs",
    "summary": "List problem logs",
    "description": "List logs for a problem.",
    "httpMethod": "GET",
    "path": "/problems/{problemId}/logs",
    "exampleInput": {
      "path": {
        "problemId": "problem_123"
      }
    }
  },
  "Problems.problemsCreateLog": {
    "operationId": "problems-createLog",
    "summary": "Create problem log",
    "description": "Create a new problem log entry.",
    "httpMethod": "POST",
    "path": "/problems/{problemId}/logs",
    "exampleInput": {
      "path": {
        "problemId": "problem_123"
      },
      "body": {
        "note": "Example",
        "date": {
          "timezone": "Europe/Warsaw",
          "dateInUsersTimezone": "2026-03-30"
        }
      }
    }
  },
  "Activities.activitiesGet": {
    "operationId": "activities-get",
    "summary": "Get activity",
    "description": "Get a single activity by ID.",
    "httpMethod": "POST",
    "path": "/activities/get",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "Activities.activitiesList": {
    "operationId": "activities-list",
    "summary": "List activities",
    "description": "List activities for the current user.",
    "httpMethod": "POST",
    "path": "/activities/list"
  },
  "Activities.activitiesCreate": {
    "operationId": "activities-create",
    "summary": "Create activity",
    "description": "Create a new activity.",
    "httpMethod": "POST",
    "path": "/activities",
    "exampleInput": {
      "body": {
        "name": "Example"
      }
    }
  },
  "Activities.activitiesUpdate": {
    "operationId": "activities-update",
    "summary": "Update activity",
    "description": "Update an existing activity.",
    "httpMethod": "PATCH",
    "path": "/activities/update",
    "exampleInput": {
      "body": {
        "id": "item_123",
        "data": {
          "name": "Example",
          "emoji": "string"
        }
      }
    }
  },
  "Activities.activitiesDelete": {
    "operationId": "activities-delete",
    "summary": "Delete activity",
    "description": "Delete an activity.",
    "httpMethod": "DELETE",
    "path": "/activities/delete",
    "exampleInput": {
      "query": {
        "id": "item_123"
      }
    }
  },
  "MacroGoals.macroGoalsDelete": {
    "operationId": "macroGoals-delete",
    "summary": "Delete macro goal",
    "description": "Delete a macro goal by ID.",
    "httpMethod": "DELETE",
    "path": "/macro/goals/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "MacroGoals.macroGoalsUpdate": {
    "operationId": "macroGoals-update",
    "summary": "Update macro goal",
    "description": "Update an existing macro goal.",
    "httpMethod": "PATCH",
    "path": "/macro/goals/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      },
      "body": {
        "data": {
          "date": {
            "timezone": "Europe/Warsaw",
            "dateInUsersTimezone": "2026-03-30"
          },
          "calories": 1
        }
      }
    }
  },
  "MacroGoals.macroGoalsGet": {
    "operationId": "macroGoals-get",
    "summary": "Get macro goal",
    "description": "Get a single macro goal by ID.",
    "httpMethod": "POST",
    "path": "/macro/goals/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "MacroGoals.macroGoalsList": {
    "operationId": "macroGoals-list",
    "summary": "List macro goals",
    "description": "List macro goals for the current user.",
    "httpMethod": "POST",
    "path": "/macro/goals/list"
  },
  "MacroGoals.macroGoalsGetForDate": {
    "operationId": "macroGoals-getForDate",
    "summary": "Get macro goal for date",
    "description": "Get the macro goal active for a date.",
    "httpMethod": "POST",
    "path": "/macro/goals/for-date",
    "exampleInput": {
      "body": {
        "date": "2026-03-30"
      }
    }
  },
  "MacroGoals.macroGoalsCreate": {
    "operationId": "macroGoals-create",
    "summary": "Create macro goal",
    "description": "Create a new macro goal for the current user.",
    "httpMethod": "POST",
    "path": "/macro/goals",
    "exampleInput": {
      "body": {
        "date": {
          "timezone": "Europe/Warsaw",
          "dateInUsersTimezone": "2026-03-30"
        }
      }
    }
  },
  "Homes.homesList": {
    "operationId": "homes-list",
    "summary": "List homes",
    "description": "List homes shared with or owned by the current user.",
    "httpMethod": "GET",
    "path": "/homes"
  },
  "Homes.homesCreate": {
    "operationId": "homes-create",
    "summary": "Create home",
    "description": "Create a home for the current user.",
    "httpMethod": "POST",
    "path": "/homes",
    "exampleInput": {
      "body": {
        "name": "Example"
      }
    }
  },
  "Homes.homesDelete": {
    "operationId": "homes-delete",
    "summary": "Delete home",
    "description": "Delete a home and its dependent rooms, floors, chores, members and invites.",
    "httpMethod": "DELETE",
    "path": "/homes/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "Homes.homesGet": {
    "operationId": "homes-get",
    "summary": "Get home",
    "description": "Fetch a single home with nested room and chore data.",
    "httpMethod": "GET",
    "path": "/homes/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "Homes.homesUpdate": {
    "operationId": "homes-update",
    "summary": "Update home",
    "description": "Update home data if user has edit permission.",
    "httpMethod": "PATCH",
    "path": "/homes/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      },
      "body": {
        "data": {
          "name": "Example"
        }
      }
    }
  },
  "Ingredients.ingredientsList": {
    "operationId": "ingredients-list",
    "summary": "List ingredients",
    "description": "List ingredients visible to the current user.",
    "httpMethod": "POST",
    "path": "/ingredients/list",
    "exampleInput": {
      "body": {
        "ingredientListId": "ingredientlist_123",
        "status": "InStock"
      }
    }
  },
  "Ingredients.ingredientsGet": {
    "operationId": "ingredients-get",
    "summary": "Get ingredient",
    "description": "Get a single ingredient by ID.",
    "httpMethod": "POST",
    "path": "/ingredients/get",
    "exampleInput": {
      "body": {
        "id": "item_123"
      }
    }
  },
  "Ingredients.ingredientsCreate": {
    "operationId": "ingredients-create",
    "summary": "Create ingredient",
    "description": "Create a new ingredient.",
    "httpMethod": "POST",
    "path": "/ingredients",
    "exampleInput": {
      "body": {
        "name": "Example"
      }
    }
  },
  "Ingredients.ingredientsUpdate": {
    "operationId": "ingredients-update",
    "summary": "Update ingredient",
    "description": "Update an existing ingredient.",
    "httpMethod": "PATCH",
    "path": "/ingredients/update",
    "exampleInput": {
      "body": {
        "id": "item_123",
        "data": {
          "name": "Example",
          "emoji": "string"
        }
      }
    }
  },
  "Ingredients.ingredientsDelete": {
    "operationId": "ingredients-delete",
    "summary": "Delete ingredient",
    "description": "Delete a single ingredient.",
    "httpMethod": "DELETE",
    "path": "/ingredients/delete",
    "exampleInput": {
      "query": {
        "id": "item_123"
      }
    }
  },
  "Ingredients.ingredientsDeleteMany": {
    "operationId": "ingredients-deleteMany",
    "summary": "Delete many ingredients",
    "description": "Delete multiple ingredients.",
    "httpMethod": "POST",
    "path": "/ingredients/delete-many",
    "exampleInput": {
      "body": {
        "ids": [
          "item_123"
        ]
      }
    }
  },
  "Ingredients.ingredientsListOrphans": {
    "operationId": "ingredients-listOrphans",
    "summary": "List orphan ingredients",
    "description": "List ingredients not assigned to any ingredient list.",
    "httpMethod": "POST",
    "path": "/ingredients/orphans"
  },
  "Ingredients.ingredientsUpdateMany": {
    "operationId": "ingredients-updateMany",
    "summary": "Update many ingredients",
    "description": "Update multiple ingredients.",
    "httpMethod": "PATCH",
    "path": "/ingredients/update-many",
    "exampleInput": {
      "body": {
        "ids": [
          "item_123"
        ],
        "data": {
          "name": "Example",
          "emoji": "string"
        }
      }
    }
  },
  "Ingredients.ingredientsAddToShoppingList": {
    "operationId": "ingredients-addToShoppingList",
    "summary": "Mark ingredients to buy",
    "description": "Mark selected ingredients as 'to buy'.",
    "httpMethod": "PATCH",
    "path": "/ingredients/add-to-shopping-list",
    "exampleInput": {
      "body": {
        "ids": [
          "item_123"
        ]
      }
    }
  },
  "Dashboards.dashboardsList": {
    "operationId": "dashboards-list",
    "summary": "List dashboards",
    "description": "List dashboards for the current user.",
    "httpMethod": "POST",
    "path": "/dashboards/list"
  },
  "Dashboards.dashboardsDelete": {
    "operationId": "dashboards-delete",
    "summary": "Delete dashboard",
    "description": "Delete a dashboard by ID.",
    "httpMethod": "DELETE",
    "path": "/dashboards/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "Dashboards.dashboardsUpdate": {
    "operationId": "dashboards-update",
    "summary": "Update dashboard",
    "description": "Update an existing dashboard.",
    "httpMethod": "PATCH",
    "path": "/dashboards/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      },
      "body": {
        "data": {
          "name": "Example",
          "json": {}
        }
      }
    }
  },
  "Dashboards.dashboardsGet": {
    "operationId": "dashboards-get",
    "summary": "Get dashboard",
    "description": "Get a single dashboard by ID.",
    "httpMethod": "POST",
    "path": "/dashboards/{id}",
    "exampleInput": {
      "path": {
        "id": "item_123"
      }
    }
  },
  "Dashboards.dashboardsCreate": {
    "operationId": "dashboards-create",
    "summary": "Create dashboard",
    "description": "Create a new dashboard.",
    "httpMethod": "POST",
    "path": "/dashboards",
    "exampleInput": {
      "body": {
        "name": "Example"
      }
    }
  }
};
